repos:
- repo: https://github.com/tcort/markdown-link-check
  rev: v3.11.2
  hooks:
    - id: markdown-link-check
      args: [-q,-c, .github/md-link-config.json,./docs/zh_cn/benchmark/evaluate_with_opencompass.md]
- repo: https://github.com/lycheeverse/lychee.git
  rev: lychee-v0.18.1
  hooks:
    - id: lychee-docker
      args: ["-c /app/lychee.toml","--no-progress", "."]
      volumes:
        - "{cwd}:/app"
