repos:
- repo: https://github.com/tcort/markdown-link-check
  rev: v3.11.2
  hooks:
    - id: markdown-link-check
      args: [-q,-c, .github/md-link-config.json,./docs/zh_cn/benchmark/evaluate_with_opencompass.md]
